apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    pantheon.project: ${PANTHEON_SITE_NAME}
    pantheon.environment: local
    pantheon.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    pantheon.service: redis
status:
  loadBalancer: {}
