apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    pantheon.project: ${PANTHEON_SITE_NAME}
    pantheon.environment: local
    pantheon.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      pantheon.project: ${PANTHEON_SITE_NAME}
      pantheon.environment: local
      pantheon.service: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pantheon.project: ${PANTHEON_SITE_NAME}
        pantheon.environment: local
        pantheon.service: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: ""
        name: mi-redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
