apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    pantheon.project: ${PANTHEON_SITE_NAME}
    pantheon.environment: local
    pantheon.service: solr
  name: solr
spec:
  ports:
    - name: "8983"
      port: 8983
      targetPort: 8983
  selector:
    pantheon.service: solr
status:
  loadBalancer: {}
