tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
brew "coreutils"
brew "direnv"
brew "imagemagick"
brew "jq"
brew "libyaml"
brew "php@7.4", link: true
brew "wget"
brew "ykneomgr"
brew "ykpers"
brew "yq"
