apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    pantheon.project: ${PANTHEON_SITE_NAME}
    pantheon.environment: local
    pantheon.service: nginx
  name: nginx
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "9222"
    port: 9222
    targetPort: 9222
  selector:
    pantheon.service: nginx
status:
  loadBalancer: {}
