# Use this docker-compose file to host the site locally
version: "3.7"
services:
  nginx:
    container_name: ${PROJECT_NAME}
    image: ${NGINX_CONTAINER}
    expose:
      - 80
      - 9222
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
    volumes:
      - ".:/var/www"
    ports:
      - "8080:80"
      - "9222:9222"
    env_file:
      - .env

  php:
    container_name: ${PROJECT_NAME}-php
    image: ${PHP_CONTAINER}
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www"
      - "$HOME/.terminus/cache:/root/.terminus/cache:cached"
      - type: bind
        source: $HOME/.ssh
        target: /root/.ssh
        read_only: true
    links:
      - redis
      - mysql
    env_file:
      - .env
    environment:
      - BACKUP_FILE_NAME=${PROJECT_NAME}.sql.gz
      - DATABASE_NAME=drupal8

  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: ${MYSQL_CONTAINER}
    # uncomment this volume to have the mysql container
    # retain it's database from run-to-run.blkio_config:
    # ideally you would power up and get a fresh db
    # with every development sprint.
    #volumes:
    # - './db:/var/lib/mysql'
    expose:
      - "3306"
    ports:
      - "33067:3306"
    env_file:
      - .env

  redis:
    # Generic redis instance
    container_name: ${PROJECT_NAME}-redis
    image: redis
    expose:
      - "6379"

## TODO: add solr service

volumes:
  web: {}
  initmysql: {}
