# Docker file for local development

version: '3.7'
services:

  mysql:
    container_name: ${DOCKER_MYSQL_CONTAINER}
    volumes:
      - db:/var/lib/mysql
    build: .
    image: ${DOCKER_REGISTRY}${DOCKER_MYSQL_IMAGE}:dev
    env_file:
      - .env
    expose:
      - "3306"
    ports:
      - "33068:3306"

volumes:
  db: {}