apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    pantheon.project: ${PANTHEON_SITE_NAME}
    pantheon.environment: local
    pantheon.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        pantheon.service: php
    spec:
      containers:
      - env:
        - name: BABEL_ENV
          valueFrom:
            configMapKeyRef:
              key: BABEL_ENV
              name: env
        - name: BACKUP_FILE_NAME
          value: backup.sql.gz
        - name: CACHE_HOST
          valueFrom:
            configMapKeyRef:
              key: CACHE_HOST
              name: env
        - name: CACHE_PORT
          valueFrom:
            configMapKeyRef:
              key: CACHE_PORT
              name: env
        - name: COMPOSER_ALLOW_SUPERUSER
          valueFrom:
            configMapKeyRef:
              key: COMPOSER_ALLOW_SUPERUSER
              name: env
        - name: DATABASE_NAME
          value: drupal8
        - name: DB_DRIVER
          valueFrom:
            configMapKeyRef:
              key: DB_DRIVER
              name: env
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: env
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: env
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: env
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: env
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: env
        - name: DRUPAL_HASH_SALT
          valueFrom:
            configMapKeyRef:
              key: DRUPAL_HASH_SALT
              name: env
        - name: DRUPAL_MAJOR_VERSION
          valueFrom:
            configMapKeyRef:
              key: DRUPAL_MAJOR_VERSION
              name: env
        - name: DRUPAL_SYSTEM_LOGGING_ERROR_LEVEL
          valueFrom:
            configMapKeyRef:
              key: DRUPAL_SYSTEM_LOGGING_ERROR_LEVEL
              name: env
        - name: DRUSH_OPTIONS_URI
          valueFrom:
            configMapKeyRef:
              key: DRUSH_OPTIONS_URI
              name: env
        - name: ENABLE_GATSBY_REFRESH_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ENABLE_GATSBY_REFRESH_ENDPOINT
              name: env
        - name: ENV
          valueFrom:
            configMapKeyRef:
              key: ENV
              name: env
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: env
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: env
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: env
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: env
        - name: PREPROCESS_CSS
          valueFrom:
            configMapKeyRef:
              key: PREPROCESS_CSS
              name: env
        - name: PREPROCESS_JS
          valueFrom:
            configMapKeyRef:
              key: PREPROCESS_JS
              name: env
        - name: PROD_PASS
          valueFrom:
            configMapKeyRef:
              key: PROD_PASS
              name: env
        - name: PROD_USER
          valueFrom:
            configMapKeyRef:
              key: PROD_USER
              name: env
        - name: SKIP_PREFLIGHT_CHECK
          valueFrom:
            configMapKeyRef:
              key: SKIP_PREFLIGHT_CHECK
              name: env
        - name: SOLR_CORE
          valueFrom:
            configMapKeyRef:
              key: SOLR_CORE
              name: env
        - name: SOLR_HOST
          valueFrom:
            configMapKeyRef:
              key: SOLR_HOST
              name: env
        - name: SOLR_PATH
          valueFrom:
            configMapKeyRef:
              key: SOLR_PATH
              name: env
        - name: SOLR_PORT
          valueFrom:
            configMapKeyRef:
              key: SOLR_PORT
              name: env
        image: milken/php-dev
        imagePullPolicy: ""
        name: mi-php
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: php-claim0
        - mountPath: /root/.terminus/cache
          name: php-claim1
        - mountPath: /root/.ssh
          name: php-claim2
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
      - name: php-claim1
        persistentVolumeClaim:
          claimName: php-claim1
      - name: php-claim2
        persistentVolumeClaim:
          claimName: php-claim2
          readOnly: true
status: {}
